Decryptor 2.0/Controllers/ProcessController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Decryptor.Models;

namespace Decryptor.Controllers
{
    public class ProcessController : Controller
    {
        public static string ProcessSystemMessage { get; set; }
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Encrypt()
        {
            Processor.NewProcessor();
            Processor.CurrentOperation = Operation.Encrypt;
            return Redirect("/Alphabet/Index");
        }
        public ActionResult Decrypt()
        {
            Processor.NewProcessor();
            Processor.CurrentOperation = Operation.Decrypt;
            return Redirect("/Alphabet/Index");
        }
        public void GenerateRandomKey()
        {
            Processor.GenerateRandomKey();
            //return EmptyResult;
        }
        public ActionResult DoOperation(string key, string inputText, string process)
        {
            if (process== "Сгенерировать ключ")
            {
                Processor.GenerateRandomKey();
                Processor.InputText = inputText;
                return Redirect("/Process/Index");
            }
            if (key=="" || key==null)
            {
                ProcessSystemMessage = "С пустым ключом текст останется незашифрованным. Оно вам надо?";
                return Redirect("/Process/Index");
            }
            if (inputText=="" || inputText== null)
            {
                ProcessSystemMessage = "Введите текст для шифрования";
                return Redirect("/Process/Index");
            }
            Processor.InputText = inputText;
            foreach(char symbol in key)
            {
                if (!Processor.EncryptionAlphabet.Contains(symbol.ToString().ToLower()))
                {
                    ProcessSystemMessage = "Ключ должен состоять только из символов алфавита Шифрования";
                    return Redirect("/Process/Index");
                }

            }
            Processor.KeyWord = key;
            Processor.OutputText = "";
            Processor.DoOperation();
            return Redirect("/Download/Index");
        }
    }
}

Decryptor 2.0/Controllers/UploadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using Decryptor.Models;

namespace Decryptor.Controllers
{
    public class UploadController : Controller
    {
        public static bool CorrecrFileUploaded { get; set; }

        [HttpGet]
        public ActionResult Index()
        {
            Processor.NewProcessor();
            return View();
        }
        [HttpGet]
        public ActionResult Encrypt()
        {
            Processor.CurrentOperation = Operation.Encrypt;
            return Redirect("/Upload/Index");
        }
        [HttpGet]
        public ActionResult Decrypt()
        {
            Processor.CurrentOperation = Operation.Decrypt;
            return Redirect("/Upload/Index");
        }
        [HttpPost]
        public ActionResult UploadFile(HttpPostedFileBase file)
        {
            try
            {
                Processor.NameOfInputFile = Path.GetFileName(file.FileName);
                Processor.PathToInputFile = Path.Combine(Server.MapPath("~/App_Data"), Processor.NameOfInputFile);
                if (Processor.NameOfInputFile==""||Processor.NameOfInputFile==null)
                {
                    ViewBag.Message = $"Выберите файл чтобы продолжить";
                    return View("~/Views/Upload/Index.cshtml");
                }
                if (Processor.NameOfInputFile.EndsWith(".txt") || Processor.NameOfInputFile.EndsWith(".docx") || Processor.NameOfInputFile.EndsWith(".doc"))
                {
                    if (file.ContentLength > 0)
                    {
                        file.SaveAs(Processor.PathToInputFile);
                    }
                }
                else
                {
                    ViewBag.Message = $"Файл имеет неподдерживаемый формат {Processor.NameOfInputFile.Substring(Processor.NameOfInputFile.LastIndexOf("."))}";
                    return View("~/Views/Upload/Index.cshtml");
                }
                if (Processor.NameOfInputFile.EndsWith(".txt"))
                {
                    Processor.InputText = Processor.ReadTXTFile(Processor.CheckFileEncoding());
                }
                if (Processor.NameOfInputFile.EndsWith(".doc") || Processor.NameOfInputFile.EndsWith(".docx"))
                {
                    Processor.InputText = Processor.ReadDOCXFile();
                }
                return Redirect("/Alphabet/Index");
            }
            catch (Exception e)
            {
                ViewBag.Message = $"Загрузка файла не удалась:  " + e.Message;
                return View("~/Views/Upload/Index.cshtml");
            }
        }
    }
}

Decryptor 2.0/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title Decryptor.Net</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Decryptor.Net", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Зашифровать текст", "Encrypt", "Process")</li>
                    <li>@Html.ActionLink("Расшифровать текст", "Decrypt", "Process")</li>
                    <li>@Html.ActionLink("Зашифровать файл", "Encrypt", "Upload")</li>
                    <li>@Html.ActionLink("Расшифровать файл", "Decrypt", "Upload")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Коваленко Антон - Decryptor.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>